---
abstract: 'IRC plugin for minismokebox'
author:
  - 'Chris Williams'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-SmokeBox-Mini-Plugin-IRC
requires:
  App::SmokeBox::Mini: 0.54
  POE: 1.28
  POE::Component::IRC: 6.16
  perl: v5.6.0
resources:
  homepage: http://github.com/bingos/app-smokebox-mini-plugin-irc
  repository: http://github.com/bingos/app-smokebox-mini-plugin-irc
version: 0.10
